### ISSUE TITLE
Still get an error but fixed the previous ones

### ISSUE THREAD

**Issue by CasualPlayer1337** [ericek111/java-csgo-externals#2]
Exception in thread "main" java.lang.RuntimeException: com.jogamp.opengl.GLException: Caught ExceptionInInitializerError: null on thread main-Display-.x11_:0.0-1-EDT-1
	at jogamp.newt.DefaultEDTUtil.invokeImpl(DefaultEDTUtil.java:252)
	at jogamp.newt.DefaultEDTUtil.invoke(DefaultEDTUtil.java:165)
	at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:442)
	at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:2782)
	at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1330)
	at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:1335)
	at com.jogamp.newt.opengl.GLWindow.setVisible(GLWindow.java:578)
	at me.lixko.csgoexternals.Engine.init(Engine.java:63)
	at me.lixko.csgoexternals.Main.main(Main.java:13)
Caused by: com.jogamp.opengl.GLException: Caught ExceptionInInitializerError: null on thread main-Display-.x11_:0.0-1-EDT-1
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:260)
	at com.jogamp.newt.opengl.GLWindow.access$200(GLWindow.java:119)
	at com.jogamp.newt.opengl.GLWindow$2.windowResized(GLWindow.java:141)
	at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:4384)
	at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:4318)
	at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:1306)
	at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:1318)
	at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:145)
	at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:375)
Caused by: java.lang.ExceptionInInitializerError
	at me.lixko.csgoexternals.JOGL2Renderer.init(JOGL2Renderer.java:80)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	... 11 more
Caused by: java.lang.NullPointerException
	at me.lixko.csgoexternals.util.DrawUtils.<clinit>(DrawUtils.java:36)
	... 16 more
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:0.0, 0x7f0754001920, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:0.0, 0x7f07540164e0, refCount 1, unCloseable false]

**Comment by ericek111** [comment]
Thanks for the issue report and stacktrace! I released a new version, you can download it by executing the `download.sh` script. If the problem occurs agian, please, make sure to post also the very **first line**, it contains the textures path (the reason why your cheat keeps crashing).

Also, double-check that you're using the latest `download.sh`.
