### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by darkzaion** [ericek111/java-csgo-externals#5]
Error when sudo ./start.sh

darkzaion@linux-42pb:~/Documentos> sudo ./start.sh 
root's password:
Caught handled GLException: EGLGLXDrawableFactory - Could not initialize shared resources for EGLGraphicsDevice[type .egl, v1.4.0, connection nil, unitID 0, handle 0x7f52bc001360, owner true, ResourceToolkitLock[obj 0x7fcfbf00, isOwner true, <9957752, 380086a8>[count 1, qsz 0, owner <main-SharedResourceRunner>]]] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createSharedResource(EGLDrawableFactory.java:518)
    [1]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [2]: java.lang.Thread.run(Unknown Source)
Caused[0] by GLException: Graphics configuration failed [direct caps, eglGetConfig/chooser and fixed-caps(1-3)] on thread main-SharedResourceRunner
    [0]: jogamp.opengl.egl.EGLGraphicsConfigurationFactory.chooseGraphicsConfigurationStatic(EGLGraphicsConfigurationFactory.java:317)
    [1]: jogamp.opengl.egl.EGLDrawableFactory.evalConfig(EGLDrawableFactory.java:1060)
    [2]: jogamp.opengl.egl.EGLDrawableFactory.createSurfacelessImpl(EGLDrawableFactory.java:1088)
    [3]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.mapAvailableEGLESConfig(EGLDrawableFactory.java:705)
    [4]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createEGLSharedResourceImpl(EGLDrawableFactory.java:613)
    [5]: jogamp.opengl.egl.EGLDrawableFactory$SharedResourceImplementation.createSharedResource(EGLDrawableFactory.java:516)
    [6]: jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:353)
    [7]: java.lang.Thread.run(Unknown Source)
Exception in thread "main" com.jogamp.nativewindow.NativeWindowException: X11Util.Display: Unable to create a display(nil) connection. Thread main
        at jogamp.nativewindow.x11.X11Util.openDisplay(X11Util.java:453)
        at jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.isDeviceSupported(X11GLXDrawableFactory.java:230)
        at jogamp.opengl.SharedResourceRunner.getOrCreateShared(SharedResourceRunner.java:224)
        at jogamp.opengl.x11.glx.X11GLXDrawableFactory.getOrCreateSharedResourceImpl(X11GLXDrawableFactory.java:371)
        at jogamp.opengl.x11.glx.X11GLXDrawableFactory.getOrCreateSharedResourceImpl(X11GLXDrawableFactory.java:81)
        at jogamp.opengl.GLDrawableFactoryImpl.getOrCreateSharedResource(GLDrawableFactoryImpl.java:187)
        at jogamp.opengl.GLDrawableFactoryImpl.createSharedResourceImpl(GLDrawableFactoryImpl.java:216)
        at com.jogamp.opengl.GLDrawableFactory.createSharedResource(GLDrawableFactory.java:381)
        at com.jogamp.opengl.GLProfile.initProfilesForDeviceCritical(GLProfile.java:1916)
        at com.jogamp.opengl.GLProfile.initProfilesForDevice(GLProfile.java:1875)
        at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1843)
        at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
        at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
        at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:988)
        at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:722)
        at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:733)
        at me.lixko.csgoexternals.Engine.init(Engine.java:58)
        at me.lixko.csgoexternals.Main.main(Main.java:13)
darkzaion@linux-42pb:~/Documentos> 
                                                                            
What could be? :P

**Comment by ericek111** [comment]
Hello,
what's your setup, please?

**Comment by darkzaion** [comment]
OpenSuse 42.2 Leap
KDE
And every thing on default installation :)
